---
title: "PS270 Final Project"
author: "Zoey Jiang"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

For this project, I will use data from a Pew Research Panel's survey on opinions toward social connections, gender roles, and specifically masculinity. My question: What is the relationship between Americans' perceptions of whether men are discriminated against in today's society and their political party affiliation?

My theory is that those who identify as Republicans are more inclined than Democrats to think that men face discrimination. Political identity theory and elite messaging, which contend that partisan parties consistently produce disparate views of societal change, serve as the foundation for my hypothesis. Concerns about shifting gender roles and perceived disadvantages for men have been more prominent in conservative political discourse, which may influence people's opinions about gender equality issues. Political party identification, as determined by Pew's party summary variable (e.g., Republican/Lean Republican, Democrat/Lean Democrat, Independent), is the main explanatory variable. This variable allows for comparisons between political groups because it shows significant variation among respondents. Survey questions asking respondents if males face "a great deal," "some," "not much," or "no" prejudice in the US are used to measure the outcome variable, perceived discrimination against men. Attitudes toward gender inequality are captured by this ordinal scale. In a regression analysis, evidence for my hypothesis would show a positive correlation between Republican identity and higher reported perceptions of discrimination against men. On the other hand, this pattern would refute the hypothesis and imply that political identity does not consistently shape opinions on men's social position if Democrats and Republicans report equal impressions, or if Democrats are more likely to detect discrimination against men.

```{r}
library(tidyverse)
library(haven)

dataset154 <- read_sav("ATP W154.sav")
head(dataset154)
```

